### ISSUE TITLE
Remove dependency to slf4j-simple

### ISSUE THREAD

**Issue by Khoulaiz** [flyway/flyway-test-extensions#22]
All your spring libraries contain a dependency to the Simple Log Implementation of SLF4J. Please remove all of them. A library should never ever come with a dependency to an slf4j log implementation. The whole purpose of slf4j is the separation of API and implementation, so that the user of the library has the ability to add the logging implementation of his choice. Because there is only one logging implementation per VM allowed, all users now are forced to explicitly exclude the simple log jar if they want a different logging implementation. 

Otherwise: Very useful extension!

Cheers,

Andreas

**Comment by FlorianGWE** [comment]
Hi Andreas, 

I got you hint. 
I plan to fix it with the next release.

florian

**Comment by FlorianGWE** [comment]
Dependency for SLF4J are removed.

Will be part of Version 3.2.1.1.
