### ISSUE TITLE
Recommended to add the remote directory scanning mechanism

### ISSUE THREAD

**Issue by 1276001750** [flyway/flyway-test-extensions#24]
Flyway now can only scan the file system path and classpath, the proposed new scan function of the remote directory.
For example, SVN

**Comment by FlorianGWE** [comment]
In my opinion is this not a feature request for flyway-test-extension.
May be this will be a feature-request for flyway (https://github.com/flyway/flyway/issues).

Test extension use flyway internall scanning functionality.

I do not understand, why a package software need for continous integration to checkout a specific set of SQL files during runtime. 
If you need a specific set of SQL scripts to set up your database, then the contious build of your application should package all data togehter. Only than you have a reproducable build and setup envrionment for your application.
