### ISSUE TITLE
Multiple database migrations in tests

### ISSUE THREAD

**Issue by tusharm** [flyway/flyway-test-extensions#37]
Hi,

My Spring Boot app needs to talk to two separate databases. Ideally, I'd like to have two separate sets of migrations, which would both be executed when I annotate my tests  with `FlywayTest`. 

The `FlywayTestExecutionListener` looks for a single Flyway bean in the context and uses it for migration. I guess I could write my own TextExecutionListener, which would get all Flyway beans in the context and `migrate` them all. Does that sound ok? - if not, what would you suggest?

Regards

**Comment by eddumelendez** [comment]
@tusharm you can set`flywayName` in `FlywayTest` with the name of your `flyway` bean.

**Comment by tusharm** [comment]
@eddumelendez I have few integration tests that need to talk to both databases. Such tests would need both the Flyway beans. I don't think the current implementation of FlywayTest/FlywayTestExecutionListener support that usecase.

**Comment by eddumelendez** [comment]
May we can use this issue for the following proposal

```
@FlywayTests(

)
```

**Comment by tusharm** [comment]
I am trying out a custom TestExecutionListener which is very similar to `FlywayTestExecutionListener`, except that it gets all beans of type Flyway.class in the context. It then processes all of them in a sequence. 

Your proposal above seems more flexible, in that I can have multiple beans in the context and still choose a few of them, as needed by my test. But this would still need a new TestExecutionListener, right?

**Comment by FlorianGWE** [comment]
Eddú it is a nice solution.

**Comment by eddumelendez** [comment]
Thanks @FlorianGWE . just noticed that I executed `mvn clean package` instead of `mvn clean install` and got some compilation errors. `AnnotatedElementUtils` was added in spring 4.0 so tests with previous versions won't pass. 😢

**Comment by FlorianGWE** [comment]
Yes, I noticed it. 

This is the reason why I not close the issue.

But I will think about a solution. 
Following options I can see at the moment

1. May be one solution is that we do not support FlywayTests in Spring version lower than 4. So flyway-spring3-test and flyway-spring2-test will contains the previous FlywayTestExecutor implementation. At the moment the source-code will copied from spring-test. Different SourceCode for the old versions. 
1. Do the scanning by our own implementation :-(
1. something else 
 
Florian

**Comment by eddumelendez** [comment]
I think that we can use `AnnotationUtils`. I will work on this in the next days.

**Comment by FlorianGWE** [comment]
Eddú great work. Thanks

**Comment by FlorianGWE** [comment]
With the new feature of annotation FlywayTests we should build a new release. -> 4.2.0.1

**Comment by FlorianGWE** [comment]
Release 4.2.0.1 is out
