### ISSUE TITLE
Add support for JUnit 5

### ISSUE THREAD

**Issue by eddumelendez** [flyway/flyway-test-extensions#43]
http://junit.org/junit5/docs/current/user-guide/#extensions

**Comment by FlorianGWE** [comment]
JUnit 5 is out so we should think about how we could integrate Flyway Test extensions in it. 
One problem could be the Spring setup of the Flyway stuff.

**Comment by JorgenRingen** [comment]
Any updates or roadmap for this? Are there any workarounds for JUnit5?

**Comment by FlorianGWE** [comment]
Hi Jørgen, 
At the moment no update or plan. Hope at the end of November I have time for flyway-test-extension.
If you have a test run with exception of spring with Junit5 it will be welcome. 
I think a Junit5 only setup will be much effort. 

Florian

**Comment by FlorianGWE** [comment]
Please take a look in the Spring5JunitTest in the example project flyway-test-junit5. 
It show how the annotation FlywayDb can be used with Junit5 and Spring5.
Note: BeforeAll is currently not implemented. 

At the moment I think about how to implement a FlywayTestExtension as a Junit5 extension.

**Comment by FlorianGWE** [comment]
I add a save load implementation for Junit5 environment without any Junit4 class. 

@JorgenRingen can you clone the repostory and make a test with 4.2.1-SNAPSHOT if the current implementation is all you currently need for your environment.

**Comment by JorgenRingen** [comment]
I can confirm that 4.2.1-SNPASHOT of flyway-spring5-test works for my usecase/environment. Thanks a lot! :-)

**Comment by FlorianGWE** [comment]
New Release 4.2.0.2 contains Junit 5 support.
